VIAL_ENABLE            = yes   # Vial protocol
VIA_ENABLE             = yes   # VIA protocol (Vial dependency)
VIALRGB_ENABLE         = yes   # Vial RGB mode/brightness controls
RGB_MATRIX_CUSTOM_USER = yes   # Includes rgb_matrix_user.inc; without this, custom effect stubs are silently dropped
ENCODER_MAP_ENABLE     = yes   # Per-layer encoder action tables
COMBO_ENABLE           = yes   # Required for Vial runtime combo editor (even with zero hardcoded combos)
TAP_DANCE_ENABLE       = yes   # Tap-dance slots configured live in Vial
KEY_OVERRIDE_ENABLE    = yes   # Key overrides; used for AltGr Swedish characters; editable in Vial
UNICODE_ENABLE         = yes   # UC() keycodes for Swedish character output
AUTO_SHIFT_ENABLE      = yes   # Hold-for-shift; threshold tunable in Vial
MOUSEKEY_ENABLE        = yes   # Mouse movement/click/scroll keycodes for NAV layer
REPEAT_KEY_ENABLE      = yes   # QK_REPEAT_KEY / QK_ALT_REPEAT_KEY
DYNAMIC_TAPPING_TERM_ENABLE = yes  # Live tapping term adjustment via DT_UP / DT_DOWN
VIAL_INSECURE          = yes   # Vial unlock without physical key combo
# CONSOLE_ENABLE       = yes   # Uncomment for debug builds only (~2 KB flash cost)
